Update lang-go.json5
giantswarm/renovate-presets pull request #4
Opened 2023-10-26 08:12 UTC by mcharriere

2023-10-27 07:05 UTC, AverageMarcus commented
@mcharriere Was this discussed yesterday?

2023-10-27 07:13 UTC, mcharriere commented
@AverageMarcus no, I didn't make it to KaaS sync. I'll bring up the topic next week. Added to the agenda

2023-10-27 07:14 UTC, AverageMarcus requested changes
Blocking merge until discussed with rest of teams. :)

2024-07-05 06:49 UTC, AverageMarcus approved these changes

2024-07-05 06:51 UTC, merged